### ISSUE TITLE
[Investigation Needed] Certain KnownPath tests fail on my Linux machine

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.Paths#24]
![20230919_14h26m56s_grim](https://github.com/Nexus-Mods/NexusMods.Paths/assets/6697380/e2ee9086-9cf1-483c-b9d8-7b7101c3891f)

I have not investigated far into this, so no further details available.
Should probably be assigned to me, as it's on my machine and CI does not encounter this.

**Comment by erri120** [comment]
Can you post the stacktrace?

**Comment by Sewer56** [comment]
It's not very useful

```
Xunit.Sdk.XunitException
Expected a <System.Exception> to be thrown, but no exception was thrown.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message)
   at FluentAssertions.Specialized.DelegateAssertionsBase`2.ThrowInternal[TException](Exception exception, String because, Object[] becauseArgs)
   at FluentAssertions.Specialized.DelegateAssertions`2.Throw[TException](String because, Object[] becauseArgs)
   at NexusMods.Paths.Tests.FileSystem.BaseFileSystemTests.Test_KnownPath(String os, KnownPath knownPath, Boolean expected) in /mnt/518e3521-5116-181b-6591-7c0c48b74c4d/Projects/NexusMods.Paths/tests/NexusMods.Paths.Tests/FileSystem/BaseFileSystemTests.cs:line 252
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Because it happens in an assert, while an exception was expected.

**Comment by erri120** [comment]
Yeah, those known paths shouldn't exist on Linux, they are Windows specific.

**Comment by Sewer56** [comment]
I can no longer repro this. :(
